# Generated by Django 3.1.7 on 2021-03-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title of tournament')),
                ('status', models.TextField(verbose_name='Status of tournament')),
                ('startTime', models.TextField(verbose_name='Date of tournament start')),
                ('gameMode', models.TextField(verbose_name='Game mode of tournament')),
                ('participant', models.TextField(verbose_name='Number of participants')),
                ('reward', models.TextField(verbose_name='Tournament reward')),
                ('siteName', models.TextField(verbose_name='Name of site')),
                ('link', models.URLField(verbose_name='URL of tournament')),
                ('dateTime', models.TextField(verbose_name='dateTime')),
            ],
        ),
    ]
