# Generated by Django 3.2.5 on 2021-07-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dota',
            name='link',
        ),
    ]
