# Generated by Django 3.2.5 on 2021-07-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0002_remove_dota_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dota',
            name='link',
            field=models.URLField(default=0, verbose_name='URL of tournament'),
            preserve_default=False,
        ),
    ]
