# Generated by Django 3.1.7 on 2021-07-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0002_auto_20210701_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota',
            name='startTime',
            field=models.DateTimeField(verbose_name='Date of tournament start'),
        ),
    ]
