# Generated by Django 3.1.7 on 2021-07-01 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0003_auto_20210701_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='dota',
            name='img',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Image of tournament'),
            preserve_default=False,
        ),
    ]
