# Generated by Django 3.1.7 on 2021-07-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0004_dota_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota',
            name='startTime',
            field=models.TextField(verbose_name='Date of tournament start'),
        ),
    ]
