# Generated by Django 3.2.5 on 2021-07-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0004_auto_20210712_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Currence of reward'),
        ),
    ]
