# Generated by Django 3.2.5 on 2021-08-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0006_auto_20210816_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota',
            name='participant',
            field=models.CharField(max_length=10, verbose_name='Number of participants'),
        ),
        migrations.AlterField(
            model_name='dota',
            name='startTime',
            field=models.CharField(max_length=15, verbose_name='Date of tournament start'),
        ),
        migrations.AlterField(
            model_name='dota',
            name='status',
            field=models.CharField(max_length=15, verbose_name='Status of tournament'),
        ),
        migrations.AlterField(
            model_name='dota',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title of tournament'),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.URLField(unique=True, verbose_name='URL of image'),
        ),
    ]
