# Generated by Django 3.2.5 on 2021-08-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0007_auto_20210816_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.CharField(max_length=15, verbose_name='Type of reward'),
        ),
    ]
