# Generated by Django 3.2.5 on 2021-09-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0008_alter_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota',
            name='startTime',
            field=models.CharField(max_length=25, verbose_name='Date of tournament start'),
        ),
    ]
