# Generated by Django 3.2.5 on 2021-09-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0011_alter_dota_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitename',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Name of the site'),
        ),
    ]
