# Generated by Django 3.2.5 on 2021-09-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0012_alter_sitename_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota',
            name='siteName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dota.sitename', unique=True),
        ),
    ]
