# Generated by Django 3.2.5 on 2021-09-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0013_alter_dota_sitename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota',
            name='siteName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dota.sitename'),
        ),
    ]
