# Generated by Django 3.2.5 on 2021-09-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0014_alter_dota_sitename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota',
            name='gameMode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameModes', to='Dota.gamemode'),
        ),
        migrations.AlterField(
            model_name='dota',
            name='siteName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteNames', to='Dota.sitename'),
        ),
    ]
