# Generated by Django 3.2.5 on 2021-09-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0015_auto_20210905_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemode',
            name='mode',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mode of the game'),
        ),
    ]
