# Generated by Django 3.2.5 on 2021-09-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0017_alter_sitename_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title of tournament'),
        ),
    ]
